controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

Home:
    path: /
    controller: App\Controller\HomeController::index

search:
    path: /search
    controller: App\Controller\SearchController::search

app_commande_success:
    path: '/commande/confirmation/{id}'
    controller: App\Controller\CommandeController::success